### PR TITLE
Add OMD-Labs Edition

### PR DESCRIPTION
**Pull request by nurse-curtis**
https://github.com/ConSol/omd-labs-docker
Open Monitoring Distribution on Debian with Ansible support.  Created custom site 'cmk' instead of the default demo.

Updated the Organizer Dockerfile version number.

### CODE REVIEW

**Comment by jordanhubbard** [comment]
Please feel free to merge your own PRs after tomorrow - I will no longer be able to do this as an iXsystems employee.

**Comment by jordanhubbard** [comment]
Also, do you have dockerhub privileges?  If not, let me know your dockerhub username and I can make sure you're set up there to add the build tasks for any and all new containers.  Thanks!

**Comment by nurse-curtis** [comment]
Jordan,

Thanks a bunch for letting me help out! I don't have build privileges on 
'freenas', if that is what you mean.  My account is 'nursecurtis' on 
dockerhub.  I'd be happy to take a more active roll!  As you can 
probably guess from my usernames, I'm actually a nurse (psychiatry), but 
also a comp-sci dropout about 15 years ago.  I'm glad to be able to 
contribute in some way to such a great project! Between Allan Jude 
(listed first only because I'm also Canadian) and Kris Moore, I feel 
like I know all of you guys, so it's nice to pay back a little bit of 
BSD-geek fan-boy appreciation!

Having heard of you moving on, if there is anything specific I can 
assist with in my spare time, I'd be happy to assist in this aspect of 
the project! Or is someone else taking the lead on this now? Good luck 
with your future endeavours!

Curtis

**Comment by nurse-curtis** [comment]
Thanks! My username on dockerhub is 'nursecurtis'.  I don't have build access to FreeNAS over there.  I'd be happy to take a more active roll with this aspect of the project!  Good luck with your future endevours!

**Comment by jordanhubbard** [comment]
You’re now added to dockerhub - you should be able to add your own containers to the freenas collection!

Thanks,

- Jordan

**Pull request merged**
