### PR TITLE
Small Fixes, One New Container

### PR DESCRIPTION
**Pull request by brando56894**
* Added PhpMyAdmin 
* Fixed ports for WordPress and LetsEncrypt containers
* Various small fixes to formatting and other things

### CODE REVIEW

**Comment by jordanhubbard** [comment]
Hmmm.  I think you need to rebase your branch.  Still all horked. :(

**Comment by brando56894** [comment]
Really? I grabbed all the commits and then created the PR and it tells me everything is fine.

**Comment by jordanhubbard** [comment]
"This branch cannot be rebased due to conflicts
Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch."

**Comment by brando56894** [comment]
Hmm, I just created an empty branch and only added phpmyadmin, letsencrypt, and wordpress. It's odd that it's showing us different things.

**Pull request closed without merging**
