### PR TITLE
Add gitlab image

### PR DESCRIPTION
**Pull request by Nekroze**
This is a simple wrapper around the [official omnibus gitlab community edition image](https://hub.docker.com/r/gitlab/gitlab-ce). It self hosts its own database.

### CODE REVIEW

**Comment by Nekroze** [comment]
I am currently building this image on the [hub](https://hub.docker.com/r/freenasnekroze/gitlab) and will test it with FreeNAS Corral Stable as soon as I resolve a drive failure on my FreeNAS install.

**Comment by Nekroze** [comment]
Having ulimit setting issues with this. I will look into it further incase additional capabilities need to be specified.
```
/opt/gitlab/embedded/bin/runsvdir-start: line 24: ulimit: pending signals: cannot modify limit: Operation not permitted                                  
/opt/gitlab/embedded/bin/runsvdir-start: line 34: ulimit: max user processes: cannot modify limit: Operation not permitted                               
/opt/gitlab/embedded/bin/runsvdir-start: line 37: /proc/sys/fs/file-max: Read-only file system
```

**Comment by animeai** [comment]
You do realise the Coral project is dead? It has been relegated to technical preview status and development efforts are entirely focussed on the 9.x branch - rebranded as 11. Docker is not yet implemented on the nightlies and VMs are iffy at best. Nobody knows how docker will work on it yet so dedicating dev work right now is a huge waste of time :(

**Comment by Nekroze** [comment]
Ha no, I missed that memo. So docker and vms are not available on freenas 11? Shame I just got a bunch of docker containers and vms now running on corral, but thanks a heap for letting me know.

**Pull request closed without merging**
