### PR TITLE
Upgrade to Subsonic 6.0

### PR DESCRIPTION
**Pull request by educatedwarrior**
This is the latest and greatest code for Subsonic.  The other Dockerfile references the older 5.0 version.   

If you would like to replace the old version let me know, or I can create a separate folder for Subsonic 6.0.  Whatever works for you guys.

### CODE REVIEW

**Comment by jordanhubbard** [comment]
Well, if it really does move things forward in the sense that Subsonic 6.0 is just way more awesomesauce than 6.0, then I suppose we should have just one image that's the latest and greatest.  However, the README.md is still too docker-y; it references docker commands that a FreeNAS user won't even know how to use (or really should), so when I'm converting containers I basically just snip all of that out and make the docs "FreeNAS-centric".

**Comment by educatedwarrior** [comment]
Sounds like a plan... I'll update the README.md when I get time this weekend.

**Comment by jordanhubbard** [comment]
I'd like to start adding contributors directly to Dockerhub so they can manage their own containers; can you send me your dockerhub username?  Thanks!

**Comment by educatedwarrior** [comment]
Hi Jordan.  My username on Dockerhub is educatedwarrior.   I’m going to commit the changes to Readme.md tonight.

**Comment by jordanhubbard** [comment]
Added to “freenas” organization - thanks!

**Comment by educatedwarrior** [comment]
Updated readme.   Ready to merge.

**Comment by jordanhubbard** [comment]
Done!

**Comment by jordanhubbard** [comment]
You can also directly check the build status for this on Dockerhub now, I hope

**Pull request merged**
