### PR TITLE
Fixed erronous commit

### PR DESCRIPTION
**Pull request by brando56894**

### CODE REVIEW

**Comment by jordanhubbard** [comment]
Shouldn't we bump or change the versions on these if we're going to rebase on different upstream containers?

**Comment by brando56894** [comment]
Yea, but the rebase was supposed to stay in my repository for testing. I never meant to push changes for nzbget, just add notes about kodi-headless. This was to fix nzbget since the container doesn't build.

**Comment by jordanhubbard** [comment]
You want to just close and do a new PR?  GitHub doesn't do partial merges..

**Comment by brando56894** [comment]
sure

**Pull request closed without merging**
