### PR TITLE
ADD: bridge mode support

### PR DESCRIPTION
**Pull request by gabrielbaez**
hey guys,  I went ahead and added the bridge mode parameter,  this allowed me to use the containers. 
-gabrielbaez

### CODE REVIEW

**Review by jordanhubbard — COMMENTED** [review]
Just to confirm: These specific docker containers absolutely refused to work with port forwarding and this change was the only way to make them work?

**Comment by gabrielbaez** [comment]
That is correct I was not able to  connect to those dockers containers until I added that option,  I'm currently using them right now.  I accidently included crushftp on this pull I removed it.   Also if you look at the forums people are having the same issues with those containers.  I got my reference on this issue by comparing with the plex container which had the bridge option added recently.

**Comment by jordanhubbard** [comment]
Sorry for the long delay on this one - it got sort of lost in the shuffle after some comments about bridge mode being "unnecessary" now that other docker changes have gone in popped up and, of course, the crushftp container got grouped into the same PR.  Is this still relevant, or can we close it and break the crushftp container into its own PR?

**Comment by gabrielbaez** [comment]
just close it all together,  I'll open a new PR when I have crushftp properly working.

**Comment by jordanhubbard** [comment]
Thanks.

**Pull request closed without merging**
