### PR TITLE
Docker images for OpenHAB and Mosquitto MQTT broker

### PR DESCRIPTION
**Pull request by bbustin**
This pull request adds FreeNAS metadata to make installing the OpenHAB home automation software and the Mosquitto MQTT broker easier on FreeNAS Corral.

Both are based on the official images from their respective projects.

### CODE REVIEW

**Comment by bbustin** [comment]
Thanks for merging this in @jordanhubbard. Neither of the two images appears to be building on Docker Hub. It may be something with the FreeNAS build settings on Docker Hub.

Is there anyone I should contact to take a look?

[freenas/mosquitto builds](https://hub.docker.com/r/freenas/mosquitto/builds/)
[freenas/openhab builds](https://hub.docker.com/r/freenas/openhab/builds/)

**Comment by jordanhubbard** [comment]
Weird, I submitted build tasks!  Let me look closer.

**Comment by bbustin** [comment]
I see the builds now. Thanks. :-)

**Comment by jordanhubbard** [comment]
Yeah, dockerhub is sometimes stupid.  :(. You add a new build task and sometimes it works great and other times you have to explicitly "trigger" it, as happened this time!

**Comment by jordanhubbard** [comment]
I'd like to start adding contributors directly to Dockerhub so they can manage their own containers; can you send me your dockerhub username?  Thanks!

**Comment by bbustin** [comment]
Hi Jordan,

My Dockerhub username is bbustin. 

- Brian

**Comment by jordanhubbard** [comment]
Added to "freenas" team - thanks!

**Pull request merged**
