### PR TITLE
added monero docker

### PR DESCRIPTION
**Pull request by pteron**
created a monero deamon docker

### CODE REVIEW

**Comment by facastagnini** [comment]
@jordanhubbard you recently invited me as a contributor, thanks a lot for that, I feel honored. I wanted to ask you what are the rules of engagement for the contributors, can we approve new docker images or just improve the current ones?

Freenas is awesome!

**Comment by jordanhubbard** [comment]
You can totally approve new docker images, improve current ones, etc.  Just do your best not to break anything because you are all "live" 😄

**Comment by jordanhubbard** [comment]
P.S. For new images, please don't forget to add a build rule on dockerhub.  I'll let you do that for this one just to get your feet wet, rather than doing it myself. ;)

**Comment by pteron** [comment]
I have a build rule on dockerhub (I think! it's at https://hub.docker.com/r/pteron/monero/) 

Do I need to create one in a freenas area?

(Sorry, still learning how all this works, but it's fun!)

**Comment by jordanhubbard** [comment]
Yes, click on organization then FreeNAS, then create build task.  Thanks!

**Comment by pteron** [comment]
I don't see FreeNAS when I click on organisations, do I need to join or do you need to add me?

**Comment by jordanhubbard** [comment]
What's your dockerhub username?  The same as here on github?

**Comment by pteron** [comment]
Yes!

**Comment by jordanhubbard** [comment]
OK, try logging out and back in to dockerhub and try again!

**Comment by pteron** [comment]
and we're in!

But when I try to create an automated build it only lets me do it from my own github linked account. I assume the freenas automated build on docker hub should build from the freenas github files...

I don't appear to be able to change the source repository to freenas/docker-images

**Pull request merged**
