### PR TITLE
Update unifi to v5.4.14

### PR DESCRIPTION
**Pull request by titanous**

### CODE REVIEW

**Comment by animeai** [comment]
Why do this and not just leave it as "Latest"? The version number is the version of the FreeNAS dockerfile, not the unifi version.

**Comment by titanous** [comment]
The confusing bit is that the FreeNAS metadata doesn't match the version being pulled in from the upstream Docker image. Does it make sense to just set the FreeNAS version to 'Latest' as well?

**Comment by titanous** [comment]
Does FreeNAS use the version metadata to allow updates? I couldn't figure out how to update in the UI.

**Comment by nurse-curtis** [comment]
I just added watchtower to the repo, which should allow this to happen automatically on the docker host. I have the feeling that leaving the FreeNAS Dockerfile to 'latest' is probably wise, then just add something like Watchtower and it will at least ensure the container is up to date anytime there is a new build.

That said, I don't know how FreeNAS handles updated containers.  I definitely haven't seen any easy way to check this or do it, other than recreating the container, which is a big PIA if there is a lot of metadata to input.

**Comment by nurse-curtis** [comment]
Anyone have a reason to not have the 'latest' container pulled?  It may be nice if the metadata version is representative of the one that it is pulling from, but someone would have to update it when necessary to keep it accurate.

**Pull request merged**
