### PR TITLE
Update CloneDeploy Version

### PR DESCRIPTION
**Pull request by cdadmin**
Fixes a permission issue with the images location when a FreeNAS dataset
is used, due to setgid not translating to the dataset properly.

### CODE REVIEW

**Comment by jordanhubbard** [comment]
I'd like to start adding contributors directly to Dockerhub so they can manage their own containers; can you send me your dockerhub username?  Thanks!

**Comment by cdadmin** [comment]
Sounds like a great idea to take some of the workload off of yourself.  My username is clonedeploy

**Comment by jordanhubbard** [comment]
Added to "freenas" team - thanks!

**Comment by cdadmin** [comment]
I just wanted to make sure I'm doing things correctly moving forward.  I can push my own docker image now directly to freenas/clonedeploy, but it is also still set to autobuild from a git push.  Should I stop submitting pull requests to git and just push directly to docker?  Thanks.

**Comment by jordanhubbard** [comment]
Hi, no, we still should go via the github workflow since otherwise there is no authoritative source for the Dockerfile other than what people push; the Dockerhub capabilities are more for new images and/or monitoring their progress of old images to make sure the builds are still working.  We can also add more github folks here as needed - let me look at the team settings!

**Pull request merged**
